FROM bozhanghpc/rexec-server:v02252025

WORKDIR /server

COPY ./rexec_server.py /server

RUN pip install dill pyzmq netCDF4 s3fs numpy matplotlib

ENV broker_addr=127.0.0.1
ENV broker_port=5560

CMD ["sh", "-c", "python rexec_server.py \
                  ${broker_addr} --broker_port ${broker_port}"]